AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for a simple Java AWS Stack
Resources:
  JavaServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-013be31976ca2c322
      KeyName: aws-java-starter
      SecurityGroups:
      - !Ref JavaServerSecurityGroup
  JavaServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified CIDR ranges
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

